import sys
import os
import json
import asyncio
import logging
from pathlib import Path

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# Add current folder to path
ROOT_DIR = Path(__file__).resolve().parent
sys.path.append(str(ROOT_DIR))

import config
import vector_store
import rag_service
from llm_provider import NvidiaProvider

TEST_QUERIES = {
    "/": "What is CittaAI company positioning and tagline?",
    "/about": "Who founded CittaAI and what is its mission?",
    "/case-studies": "Give examples of CittaAI case study results and ROI.",
    "/contact": "What is CittaAI email address and telephone number?",
    "/products/influencer-marketing": "How does creator campaigns discovery work in CittaAI?",
    "/products/whatsapp-marketing": "How does the WhatsApp Marketing platform work?",
    "/recognition": "What awards has CittaAI won?",
    "/solutions/ecommerce-os": "What is CittaAI E-Commerce OS solution?",
    "/solutions/education-os": "What features does Education OS LMS offer?",
    "/solutions/enterprise-ai-os": "What is the CittaAI Enterprise AI OS platform?",
    "/solutions/pharma-os": "What is the Pharma OS solution offered by CittaAI?",
    "/solutions/real-estate-os": "What is CittaAI Real Estate OS platform?",
    "/solutions/smart-cities-os": "What is Smart Cities OS utility management?"
}

async def main():
    logger.info("Initializing RAG validation suite...")
    
    # 1. Load static routes
    try:
        from static_data import get_static_data
    except ImportError:
        from backend.static_data import get_static_data

    sd = get_static_data()
    routes = sd.get("navigation_routes", []) + sd.get("service_routes", []) + sd.get("product_routes", [])
    routes = sorted(list(set(routes)))
    
    # Initialize RAG & vector store
    vstore = vector_store.VectorStore()
    provider = NvidiaProvider()
    rag_serv = rag_service.RAGService(provider=provider, vector_store=vstore)

    logger.info(f"Auditing knowledge coverage across {len(routes)} navigation routes...")
    
    coverage_rows = []
    
    for route in routes:
        if not route:
            continue
            
        # Count chunks
        count = vstore.get_chunk_count_for_page(route)
        indexed_status = "✅" if count > 0 else "❌"
        status_text = "Healthy" if count > 0 else "Missing"
        
        confidence_text = "—"
        if count > 0 and route in TEST_QUERIES:
            test_q = TEST_QUERIES[route]
            try:
                # Calculate confidence score via query embedding and hybrid search
                emb = await rag_serv.get_embedding(test_q, input_type="query")
                res = vstore.query_hybrid(test_q, emb, top_k=1)
                if res:
                    score = res[0]["score"]
                    confidence_text = f"{score:.4f}"
                    # Flag low confidence matches
                    if score < config.CONFIDENCE_THRESHOLD:
                        status_text = f"Low Conf ({score:.2f})"
                else:
                    confidence_text = "0.0000"
                    status_text = "No Search Match"
            except Exception as e:
                confidence_text = "Error"
                status_text = f"Err: {str(e)[:15]}"
                
        coverage_rows.append({
            "page": route,
            "indexed": indexed_status,
            "chunks": count,
            "confidence": confidence_text,
            "status": status_text
        })
        
    # Generate Markdown Report
    report_md = [
        "# Knowledge Coverage & RAG Alignment Report",
        "",
        "This report is dynamically generated by the RAG validation suite to audit database coverage, route integrity, and retrieval confidence statistics.",
        "",
        "## Knowledge Index Coverage Matrix",
        "",
        "| Route | Indexed | Chunks | Confidence Test | Status |",
        "| :--- | :---: | :---: | :---: | :--- |"
    ]
    
    for row in coverage_rows:
        report_md.append(
            f"| {row['page']} | {row['indexed']} | {row['chunks']} | {row['confidence']} | {row['status']} |"
        )
        
    report_md.append("")
    report_md.append("## Findings Summary")
    
    total_routes = len(routes)
    indexed_count = sum(1 for r in coverage_rows if r["chunks"] > 0)
    missing_count = total_routes - indexed_count
    
    report_md.append(f"- **Total Checked Navigation Routes**: {total_routes}")
    report_md.append(f"- **Indexed and Searchable Pages**: {indexed_count} ({indexed_count/total_routes*100:.1f}%)")
    report_md.append(f"- **Missing Pages / Pending Content Pages**: {missing_count} ({missing_count/total_routes*100:.1f}%)")
    
    report_text = "\n".join(report_md)
    try:
        print(report_text)
    except UnicodeEncodeError:
        # Fallback to ascii representation for terminal printing
        ascii_text = report_text.replace("✅", "[YES]").replace("❌", "[NO]")
        print(ascii_text)
    
    # Save to artifacts folder
    artifact_path = (
        "C:/Users/Rohan chilukuri/.gemini/antigravity-ide/brain/80e7d2bf-3679-484b-bd2d-106f5b0aa263/"
        "knowledge_coverage_report.md"
    )
    try:
        with open(artifact_path, "w", encoding="utf-8") as f:
            f.write(report_text)
        logger.info(f"Saved validation report to artifacts: {artifact_path}")
    except Exception as e:
        logger.error(f"Failed to save report to artifacts folder: {e}")

if __name__ == "__main__":
    asyncio.run(main())
